/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:077ffd7a-9a6a-4ed6-95af-4c4f6ebc0cbe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u8AIls21u",
    "aws_user_pools_web_client_id": "1harqnr6q6am5cvdeji5ojqeev",
    "oauth": {}
};


export default awsmobile;
